# Generated by Django 4.1.7 on 2023-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colegio', '0003_problema_delete_curso_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problema',
            old_name='instrumento',
            new_name='materia',
        ),
        migrations.AlterField(
            model_name='problema',
            name='precio',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='problema',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
